import type { Package } from "./types";

export const packages: Package[] = [
  {
    slug: "drizzle",
    name: "drizzle-orm",
    summary: "A TypeScript ORM that stays out of your way.",
    why: "It is the first ORM that has not eventually made me want to write raw SQL instead. The query builder is thin, the types are honest, and the migrations are diffs you can read.",
    url: "https://orm.drizzle.team",
    npm: "drizzle-orm",
    repo: "https://github.com/drizzle-team/drizzle-orm",
    tags: ["database", "typescript", "orm"],
    alternatives: ["prisma", "kysely"],
    relatedWriting: ["postgres-pooling-in-2026", "the-cost-of-a-thousand-pods"],
  },
  {
    slug: "hono",
    name: "hono",
    summary: "A small, fast web framework for the edge.",
    why: "It compiles to whatever runtime you point it at — Workers, Deno, Bun, Node — without pretending the differences do not exist. The middleware story is small enough to hold in your head.",
    url: "https://hono.dev",
    npm: "hono",
    tags: ["http", "edge", "typescript"],
    alternatives: ["express", "fastify", "elysia"],
    relatedWriting: ["type-driven-infra"],
  },
  {
    slug: "vitest",
    name: "vitest",
    summary: "A test runner that does not get in the way.",
    why: "Watch mode is so fast it changes how you write tests. The fact that it shares Vite's config means there is one resolver to debug, not two.",
    url: "https://vitest.dev",
    npm: "vitest",
    tags: ["testing", "tooling"],
    alternatives: ["jest", "node:test"],
    relatedWriting: ["the-quiet-case-for-monorepos"],
  },
  {
    slug: "biome",
    name: "biome",
    summary: "A formatter and linter written in Rust. One tool, no plugins.",
    why: "Replaces eslint plus prettier plus their twelve plugins with a single binary. The opinions are sensible. The speed makes you stop noticing the tool exists, which is the goal.",
    url: "https://biomejs.dev",
    npm: "@biomejs/biome",
    tags: ["linting", "formatting", "tooling"],
    alternatives: ["eslint", "prettier"],
    relatedWriting: ["the-quiet-case-for-monorepos"],
  },
  {
    slug: "sst",
    name: "sst",
    summary: "Infrastructure as a TypeScript program.",
    why: "The first IaC tool where the code you write and the code that runs are the same thing. The Pulumi-on-Workers rewrite made it feel like a serious production tool.",
    url: "https://sst.dev",
    npm: "sst",
    tags: ["devops", "iac", "typescript"],
    alternatives: ["pulumi", "cdk", "terraform"],
    relatedWriting: ["type-driven-infra"],
  },
  {
    slug: "k6",
    name: "k6",
    summary: "Load testing as a scriptable, observable thing.",
    why: "Most load testing tools want you to learn a DSL. k6 wants you to write JavaScript and get back metrics that look like every other metric you already have.",
    url: "https://k6.io",
    tags: ["testing", "performance"],
    alternatives: ["artillery", "wrk"],
    relatedWriting: ["the-cost-of-a-thousand-pods"],
  },
  {
    slug: "tigerbeetle",
    name: "tigerbeetle",
    summary: "A purpose-built database for financial transactions.",
    why: "Reading their design docs is the single most educational thing I have done this year, even if I never deploy it. The discipline of writing software that cannot be wrong about money is something every backend engineer should sit with.",
    url: "https://tigerbeetle.com",
    tags: ["database", "distributed-systems"],
    relatedWriting: ["the-cost-of-a-thousand-pods"],
  },
  {
    slug: "neon",
    name: "neon",
    summary: "Serverless Postgres with branching.",
    why: "Branching a database for every preview deploy used to be a wish. Now it is a default. The pooler is good enough that I have stopped thinking about connections for prototypes.",
    url: "https://neon.tech",
    tags: ["database", "postgres", "serverless"],
    alternatives: ["supabase", "planetscale"],
    relatedWriting: ["postgres-pooling-in-2026"],
  },
  {
    slug: "tsx",
    name: "tsx",
    summary: "Run TypeScript files directly, like node script.ts.",
    why: "Removes the build step from the inner loop of writing small scripts. The amount of yak I no longer shave to run a one-off file has been transformative.",
    url: "https://tsx.is",
    npm: "tsx",
    tags: ["tooling", "typescript"],
    alternatives: ["ts-node", "bun", "deno"],
  },
  {
    slug: "zod",
    name: "zod",
    summary: "Schema validation that the type system can read.",
    why: "The right answer for the boundary between your code and the rest of the world. The fact that it doubles as a type generator means you stop maintaining two definitions of the same thing.",
    url: "https://zod.dev",
    npm: "zod",
    tags: ["validation", "typescript"],
    alternatives: ["valibot", "yup", "arktype"],
  },
];
